name: .NET

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:act-latest
      options: --privileged

    services:
      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.9.2
        env:
          discovery.type: single-node
          xpack.security.enabled: false
          ES_JAVA_OPTS: "-Xms512m -Xmx512m"
          bootstrap.memory_lock: true
        ports:
          - 9200:9200
        options: >-
          --health-cmd "curl --silent --fail localhost:9200/_cluster/health || exit 1"
          --health-interval 30s
          --health-timeout 30s
          --health-retries 5
          --health-start-period 30s

    steps:
      - uses: actions/checkout@v3

      - name: Setup curl for health checks
        run: |
          apt-get update
          apt-get install -y curl

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Wait for Elasticsearch
        run: |
          until curl --silent --fail http://elasticsearch:9200/_cluster/health; do
            echo 'Waiting for Elasticsearch...'
            sleep 5
          done

      - name: Test
        run: dotnet test --no-build --verbosity normal
        env:
          ELASTICSEARCH_URL: http://elasticsearch:9200
